---
abstract: 'A SMS::Send driver for smstrade.de'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  English: 0
  File::Spec: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-Send-Smstrade
requires:
  LWP::UserAgent: 0
  SMS::Send::Driver: 0
  URI::Escape: 0
  parent: 0
version: 0.03
